name: Deploy OpenSaaS to Coolify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # YENİ EKLENEN ADIM BURASI
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Wasp'ın istediği 22.12.0 veya üstü bir versiyonu kuruyoruz.

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Wasp app
        working-directory: ./template/app
        run: |
          curl -sSL https://get.wasp-lang.dev/installer.sh | sh
          wasp build

      - name: Build and push server Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./template/app
          file: ./template/app/.wasp/build/Dockerfile
          push: true
          tags: ghcr.io/hemidzada/opensaas-server:main

      - name: Create client Dockerfile
        run: |
          cat > client.Dockerfile <<EOF
          FROM nginx:alpine
          COPY ./template/app/.wasp/build/web-app/build /usr/share/nginx/html
          EOF
          
      - name: Build and push client Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: client.Dockerfile
          push: true
          tags: ghcr.io/hemidzada/opensaas-client:main

      - name: Trigger Coolify server deploy
        run: curl -X POST ${{ secrets.SERVER_COOLIFY_WEBHOOK }}

      - name: Trigger Coolify client deploy
        run: curl -X POST ${{ secrets.CLIENT_COOLIFY_WEBHOOK }}
