name: Deploy OpenSaaS to Coolify (All-in-One)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- 1. Projeyi Derle ---
      - name: Install Dependencies and Build Project
        run: |
          cd ./template/app
          npm install
          curl -sSL https://get.wasp-lang.dev/installer.sh | sh
          /home/runner/.local/bin/wasp build

      # --- 2. Sunucu (Server) İmajını Oluştur ve Yükle ---
      - name: Build and Push Server Image
        run: |
          # Sunucu için Dockerfile'ı anlık olarak oluşturuyoruz
          cat > Dockerfile.server <<EOF
          FROM node:22-slim
          WORKDIR /app
          # NIHAI DÜZELTME: Kopyalama yolunun başındaki nokta kaldırıldı.
          COPY template/app/.wasp/build/server/ ./
          ENV NODE_ENV=production
          ENV PORT=3001
          EXPOSE 3001
          CMD ["node", "src/index.js"]
          EOF

          # İmajı oluşturup GitHub'a yüklüyoruz
          docker buildx build \
            --file ./Dockerfile.server \
            --tag ghcr.io/hemidzada/opensaas-server:main \
            --push .

      # --- 3. İstemci (Client) İmajını Oluştur ve Yükle ---
      - name: Build and Push Client Image
        run: |
          # İstemci için Dockerfile'ı anlık olarak oluşturuyoruz
          cat > Dockerfile.client <<EOF
          FROM nginx:alpine
          COPY ./template/app/.wasp/build/web-app /usr/share/nginx/html
          EOF

          # İstemci imajını oluşturup GitHub'a yüklüyoruz
          docker buildx build \
            --file ./Dockerfile.client \
            --tag ghcr.io/hemidzada/opensaas-client:main \
            --push .
      
      # --- 4. Coolify'i Tetikle ---
      - name: Trigger Coolify Deploys
        run: |
          curl -X POST ${{ secrets.SERVER_COOLIFY_WEBHOOK }}
          curl -X POST ${{ secrets.CLIENT_COOLIFY_WEBHOOK }}
