name: Deploy OpenSaaS to Coolify (Final & Verified)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: opensaas
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for PostgreSQL
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Install, Create Migrations, and Build
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/opensaas
        run: |
          cd ./template/app
          npm install
          curl -sSL https://get.wasp-lang.dev/installer.sh | sh
          /home/runner/.local/bin/wasp db migrate-dev --name init --create-only || echo "Migrations folder might already exist, continuing."
          /home/runner/.local/bin/wasp build

      - name: Build and Push Server Image
        run: |
          # Sunucu için, tüm düzeltmeleri içeren Dockerfile'ı anlık oluşturuyoruz
          cat > Dockerfile.server <<EOF
          FROM node:22-slim
          WORKDIR /app
          COPY --from=builder /app/.wasp/build/server/ ./
          COPY --from=builder /app/migrations ./migrations
          ENV NODE_ENV=production
          ENV PORT=3001
          EXPOSE 3001
          CMD ["sh", "-c", "npx prisma migrate deploy && node src/index.js"]
          EOF

          # Docker imajını, build context'ini doğru vererek oluşturuyoruz
          docker buildx build \
            --file ./Dockerfile.server \
            --tag ghcr.io/hemidzada/opensaas-server:main \
            --build-context builder=./template/app \
            --push .

      - name: Build and Push Client Image
        run: |
          # Önce client'ın production build'ini alıyoruz
          cd ./template/app/.wasp/build/web-app
          REACT_APP_API_URL=https://api.vidhub.ai npm run build
          
          # Dockerfile'ı ana dizinde oluşturuyoruz
          cd ../../../../
          cat > Dockerfile.client <<EOF
          FROM pierrezemb/gostatic
          CMD ["-fallback", "index.html"]
          COPY ./template/app/.wasp/build/web-app/build /srv/http
          EOF

          # İmajı ana dizinden oluşturup yüklüyoruz
          docker buildx build \
            --file ./Dockerfile.client \
            --tag ghcr.io/hemidzada/opensaas-client:main \
            --push .
      
      - name: Trigger Coolify Deploys
        run: |
          curl -X POST ${{ secrets.SERVER_COOLIFY_WEBHOOK }} --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
          curl -X POST ${{ secrets.CLIENT_COOLIFY_WEBHOOK }} --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
