name: Deploy OpenSaaS to Coolify

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db # <--- Veritabanı adı 'db'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install, Build, and Create Migrations
        env:
          # NIHAI DÜZELTME: Veritabanı URL'sinin sonuna veritabanı adını ekliyoruz.
          DATABASE_URL: postgresql://user:password@localhost:5432/db
        run: |
          cd ./template/app
          npm install
          curl -sSL https://get.wasp-lang.dev/installer.sh | sh
          
          echo "init" | /home/runner/.local/bin/wasp db migrate-dev
          
          /home/runner/.local/bin/wasp build
          
          echo "Building client for production..."
          cd ./.wasp/build/web-app
          REACT_APP_API_URL=https://api.vidhub.ai npm run build

      - name: Fix Server Dockerfile and Build/Push Image
        run: |
          sed -i '/CMD \["npm", "run", "start-production"\]/i RUN npx prisma migrate deploy --schema=../db/schema.prisma' ./template/app/.wasp/build/Dockerfile
          
          docker buildx build \
            --file ./template/app/.wasp/build/Dockerfile \
            --tag ghcr.io/hemidzada/opensaas-server:main \
            --push ./template/app
            
      - name: Build and Push Client Image
        run: |
          cat > Dockerfile.client <<EOF
          FROM pierrezemb/gostatic
          CMD ["-fallback", "index.html"]
          COPY ./build /srv/http
          EOF

          docker buildx build \
            --file ./Dockerfile.client \
            --tag ghcr.io/hemidzada/opensaas-client:main \
            --push ./template/app/.wasp/build/web-app
      
      - name: Trigger Coolify Deploys
        run: |
          curl -X POST ${{ secrets.SERVER_COOLIFY_WEBHOOK }}
          curl -X POST ${{ secrets.CLIENT_COOLIFY_WEBHOOK }}
